#!/bin/bash

source /config.saved

if [ "$BACKUP_DAILY" == "" ]; then
    rm -f /etc/cron.d/backup_job
    exit 0
fi


if [ ! -d $BACKUP_PATH ]; then
    echo "BACKUP_PATH is not set or does not exist. Please bind a volume and set BACKUP_PATH accordingly."
    exit 0
fi

# change the timezone
rm /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime

# set a cron job 
chmod +x /srv/scripts/backup_script
echo "00 00 * * * root bash -c /srv/scripts/backup_script" > /etc/cron.d/backup_job